spring.main.web-application-type=NONE
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.omnrwovhmuricmmikesv&password=mydb1234!@#$
# spring.datasource.username=root
# spring.datasource.password=
